set shell := ["nu", "-c"]

test: test_unit test_integration

test_unit:

test_integration target="" show="all" *flags="":
    @ echo "Run Integration Tests"
    @ echo "---------------------"
    @ pytest -m "not off" -x --ignore=src/legacy -p no:warnings --show-capture={{show}} --failed-first {{flags}} tests/{{target}}

run: build
    @ ./bin/gfa.exe

build:
    @ dotnet.exe build -o bin
